# Site settings
title: "La Coroutine - Créer, Apprendre, Partager"
email: contact@lacorotuine.org
description: > # this means to ignore newlines until "baseurl:"
  Un espace de coworking convivial créé, géré et financé par ses usagers pour créer
  travailler, bidouiller, apprendre, innover, partager, échanger, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lacoroutine.org" # the base hostname & protocol for your site
twitter_username: lacoroutine
github_username: la-coroutine

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
